stages:
  - build
  - deploy

variables:
  STORAGE_DRIVER: vfs
  BUILDAH_FORMAT: docker
  IMAGE_NAME: "my-app-nginx"
  FQ_IMAGE_NAME: "d051a/$IMAGE_NAME:$CI_COMMIT_REF_NAME"

build:
  stage: build
  image: quay.io/buildah/stable
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | buildah login --username "$CI_REGISTRY_USER" --password-stdin docker.io
  script:
    # Собираем и пушим образ
    - buildah images
    - buildah bud -t $FQ_IMAGE_NAME --from=docker.io/nginx:latest .
    - buildah images
    - buildah push $FQ_IMAGE_NAME
  rules:
    - when: always  # Запуск при любом коммите

deploy:
  stage: deploy
  image: ubuntu:22.04
  before_script:
    # Устанавливаем kubectl
    - apt update
    - apt install -y curl
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - kubectl config view
  script:
    # Деплой в Kubernetes
    - kubectl --kubeconfig=$KUBE_CONFIG set image deployment/my-nginx my-nginx=$FQ_IMAGE_NAME
  rules:
    - if: $CI_COMMIT_TAG  # Запуск только при создании тега 